spring:
  h2:
    console:
      path: /console
      enabled: true
  security:
    user:
      name: halfdev
      password: 1234
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    root: debug